### PR TITLE
Fix error when classpath includes a multi-release JAR

### LINKED ISSUE #13: Build fails with exposed dependency
Issue:
  Trying to build a minimal kotlin project with bazel fails if I include Exposed as a dependency. 
  If I remove "@maven//:org_jetbrains_exposed_exposed" from the BUILD file, the build will complete successfully.

Environment:
  OSX 10.13.6
  Bazel Build label: 0.27.0

---
Build command used and bazel build output:

samis-mbp-2:kot sami$ bazel build exposed:exposed --verbose_failures
INFO: Analyzed target //exposed:exposed (89 packages loaded, 877 targets configured).
INFO: Found 1 target...
ERROR: /Users/sami/dev/quant/kot/exposed/BUILD:5:1: Compiling Kotlin to JVM //exposed:exposed_lib { kt: 1, java: 0, srcjars: 0 } failed (Exit 2): builder failed: error executing command 
  (cd /private/var/tmp/_bazel_sami/c9b70ca58e43aa08a870ac9e92a6cedc/execroot/__main__ && \
  exec env - \
    LC_CTYPE=en_US.UTF-8 \
  bazel-out/host/bin/external/io_bazel_rules_kotlin/src/main/kotlin/builder '--flagfile=bazel-out/darwin-fastbuild/bin/exposed/exposed_lib.jar-0.params')
Execution platform: @bazel_tools//platforms:host_platform
Target //exposed:exposed failed to build
INFO: Elapsed time: 20.180s, Critical Path: 18.56s
INFO: 17 processes: 13 darwin-sandbox, 4 worker.
FAILED: Build did NOT complete successfully

---
The minimal project used to replicate the problem:
  [WORKSPACE.txt](https://github.com/cgruber/rules_kotlin/files/3335935/WORKSPACE.txt)
  [BUILD.txt](https://github.com/cgruber/rules_kotlin/files/3335936/BUILD.txt)
  [Exposed.kt.txt](https://github.com/cgruber/rules_kotlin/files/3335938/Exposed.kt.txt)

### PR DESCRIPTION
**Pull request by puffnfresh**
Figured this out by looking at the output of the command.

Fixes #13

### CODE REVIEW

File: src/main/kotlin/io/bazel/kotlin/builder/tasks/jvm/JDepsGenerator.kt [hunk 1]
```diff
@@ -53,6 +53,7 @@ internal class JDepsGenerator @Inject constructor(
                         val joinedClasspath = command.inputs.joinedClasspath
                         val res = invoker.run(
                             arrayOf(
+                                "--multi-release", "base",
```
Comment (puffnfresh) [inline src/main/kotlin/io/bazel/kotlin/builder/tasks/jvm/JDepsGenerator.kt]: Setting "base" means we use `java.util.jar.JarFile.baseVersion()` - is that a good value?

Do we need to guard this in case the flag is not present on older versions?

Comment (puffnfresh) [reply src/main/kotlin/io/bazel/kotlin/builder/tasks/jvm/JDepsGenerator.kt]: Yes, added a guard.

Comment (cgruber) [reply src/main/kotlin/io/bazel/kotlin/builder/tasks/jvm/JDepsGenerator.kt]: Yeah, we definitely need the guard.

**Comment by cgruber** [comment]
Hey - this looks great!  Thanks for pushing on this.  I'll roll a small release later this week, including this, plus incorporating some fixes from bazelbuild/rules_kotlin:master.
